# Generated by Django 3.0.7 on 2020-06-29 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date ajout')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
